Hunter87ff/Spruce

src/core/moderation.py

Fixed unwanted error alert of clear command. 
Added a separate exception handling for purge.
as it might throw exception while it gets overlaped by any other bot's command or trying to delete a message which is already deleted.
> Here is the code block
```py
try:
_purged = await  ctx.channel.purge(
limit=amount,
check=lambda message:self.bot.is_ws_ratelimited()==False and message,
reason=f"Clearing {amount} messages for {ctx.author}"
)
except Exception as e:
await self.bot.error_log(str(e)) #Log the issue! instead of sending to server report multiple time.
```

Fixed an issue of runtime exception of clear command

---

src/core/tourney.py
src/main.py

This pull request focuses on fixing #66 , adding detailed docstrings to various asynchronous functions in the `src/core/tourney.py` file to improve code readability and maintainability. Additionally, a minor comment was added in `src/main.py` to clarify the purpose of a specific block of code. Below are the most important changes grouped by theme:
* Added comprehensive docstrings to several functions in `src/core/tourney.py`, including `delete_tourney_confirm`, `delete_t_confirmed`, `publish`, `c_ch`, `ttl_slot`, `mnts`, `strtps`, `conro`, `spg_change`, and `export_event_data_callback`. These docstrings explain the purpose, parameters, return values, and side effects of each function, significantly improving code clarity. [[1]](diffhunk://#diff-c65bcfa3212bf27afb8c378b69f6afb29f619791a23db …

Fixed invalid interaction handling, improve few event managing view and readability 

---

src/core/dev.py
src/core/tourney.py
src/ext/__init__.py
src/ext/modals.py
src/ext/permissions.py

This pull request introduces several changes to enhance functionality, improve error handling, and refactor existing code for better readability and maintainability. The most significant updates include adding a new `teams` command, improving permissions handling, and enhancing the `Tourney` class with additional methods.
* Added a new `teams` command in `src/core/dev.py` to fetch and display team information for a specific tournament registration channel. This includes validation for event and confirmation channel existence.
* Enhanced error messages in the `dbupdate` command to provide more context when an update fails.
* Added a permission check in `src/core/tourney.py` to ensure the bot can read message history in the confirmation channel before processing event data.
* Refactored the …

Add teams command to dev cog and enhance tourney permissions checks

---

src/core/tourney.py
src/ext/modals.py
src/modules/message_handle.py

This pull request makes several improvements to variable naming, code readability, and functionality in the `src/core/tourney.py`, `src/ext/modals.py`, and `src/modules/message_handle.py` files. The most significant changes include renaming variables for clarity, improving embed construction readability, adding new methods to the `Tourney` class for better database interaction, and enhancing avatar handling for Discord embeds.
* Renamed variables in `async def auto_group` for better clarity, such as `spg` to `slot_per_group` and `cgp` to `current_group_position`. Adjusted all related references accordingly. [[1]](diffhunk://#diff-c65bcfa3212bf27afb8c378b69f6afb29f619791a23dbe37ccc88f0938f1e381L1105-R1106) [[2]](diffhunk://#diff-c65bcfa3212bf27afb8c378b69f6afb29f619791a23dbe37ccc88f0938f1e3 …

Updated  tournament wrapper for better readability and centralization and configured new view based registration

---

.github/workflows/py_application.yml
README.md
src/cogs/__init__.py
src/cogs/channel.py
src/cogs/helpcog.py
src/cogs/moderation.py
src/cogs/music.py
src/cogs/role.py
src/cogs/scrim.py
src/cogs/tasks.py
src/cogs/tourney.py
src/cogs/utility.py
src/ext/__init__.py
src/ext/error.py
src/ext/helper.py
src/ext/logger.py
src/main.py
src/modules/bot.py
src/modules/chat.py
src/modules/config.py

This pull request introduces several updates aimed at improving code maintainability, consistency, and functionality. The changes include replacing hardcoded configuration references with dynamic ones, improving logging messages, and refactoring imports for better organization. Additionally, minor adjustments were made to documentation and workflows.
* Replaced `config` module references (e.g., `config.prefix` and `config.tick`) with dynamic references to `self.bot.config` or `self.bot.emoji` for better encapsulation and flexibility. (`src/cogs/channel.py`: [[1]](diffhunk://#diff-bb7bb1a3d26d5f92ee01ec0de50297c4b262658a0b9cc0cef44f0effe9dcd882L35-R38) [[2]](diffhunk://#diff-bb7bb1a3d26d5f92ee01ec0de50297c4b262658a0b9cc0cef44f0effe9dcd882L52-R50) …

Refactors the codebase to standardize environment variable naming conventions. and overall optimization

---

pyproject.toml
src/ext/db.py
src/main.py
src/modules/chat.py
src/modules/config.py
src/modules/payment.py
uv.lock

Revert "updated Configurations, Databse and error handlers "

---

src/cogs/tourney.py
src/ext/helper.py
src/modules/message_handle.py

This pull request introduces significant updates to the tournament management system, focusing on improving logging, modularizing channel management, and enhancing code clarity. Key changes include the addition of a tournament log feature, refactoring channel locking/unlocking logic, and improving type annotations for better code maintainability.
* Introduced a `get_tourney_log` helper function in `src/ext/helper.py` to retrieve or identify the tournament log channel.
* Added logging functionality to the `tourney` function in `src/modules/message_handle.py` to record key events such as registration attempts, errors, and status updates in the tournament log channel. [[1]](diffhunk://#diff-656eec1b7a1b1dc12442dcb7e55e9c4ed2e90962c0b98e70a06ee038a4d6d7bfR169-R184) …

Enhance tourney logging functionality and permissions management; add setup command for tourney log channel

---

src/cogs/scrim.py
src/cogs/tourney.py
src/cogs/utility.py
src/ext/error.py
src/ext/models/scrim.py
src/ext/permissions.py
src/ext/time.py
src/modules/message_handle.py

This pull request introduces several updates across multiple modules, focusing on improving functionality, fixing bugs, and enhancing code readability. The most significant changes include updates to tournament eligibility criteria, adjustments to invitation creation, modifications to error handling, enhancements to the scrim model, and new utility functions for time management.
* Updated the `is_eligible` method in `src/cogs/tourney.py` to include stricter conditions for tournament eligibility, such as requiring at least 40 registered users and creation within the last 30 days.
* Simplified the `create_invite` method by reducing parameters, setting `max_age` to 3600 seconds, and retaining the `unique` flag.
* Improved error handling in `src/ext/error.py` by using `str(error)` for better …

feat(scrim): Enhance scrim management with new commands and features, updated tourneys list criteria

---

src/cogs/utility.py
src/ext/helper.py

This pull request includes updates to improve default behavior and enhance code security. The most important changes involve modifying a default color option in an embed command and refining a regex pattern to prevent potential issues.
* [`src/cogs/utility.py`](diffhunk://#diff-f2604db4155903f4e3daa29146264560613ef6d7ce8cab3ae70c98853a8a5838L187-R187): Changed the default `color` parameter in the `embed_command` function from `color.random()` to `ColorOptions.teal` for more consistent and predictable behavior.
* [`src/ext/helper.py`](diffhunk://#diff-e856d0e1117ff8469a7725cecc2ea104054a54cebef4c42a69354a863981068eL75-R80): Refined the regex pattern in the `parse_prize_pool` function by removing unnecessary characters and ensuring a secure and efficient pattern to prevent potential ReDoS …

Enhance prize pool parsing with additional input sanitization and secure regex pattern

---

.github/workflows/py_application.yml
.gitignore
README.md
changes.md
pyproject.toml
src/cogs/esports/scrim.py
src/cogs/utility.py
src/ext/helper.py
src/ext/models/scrim.py
src/modules/bot.py
src/modules/config.py
src/modules/message_handle.py

This pull request introduces significant updates to the `Spruce` Discord bot, focusing on enhancing esports management features, improving utility commands, and optimizing the codebase. Key highlights include the addition of scrim management functionalities, a complete overhaul of tournament management, and the removal of the music module to prioritize core esports capabilities.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L4-R6): Updated badges to reflect compatibility with Python 3.11+ and discord.py 2.5.2. Revised descriptions to emphasize esports management and added scrim management as a new feature. Deprecated the music module. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L4-R6) …

New Release v2.0.1

---

src/cogs/esports/scrim.py
src/cogs/esports/tourney.py
src/ext/helper.py
src/ext/models/__init__.py
src/ext/models/tournament.py
src/main.py
src/modules/bot.py
src/modules/message_handle.py

This pull request introduces several improvements and fixes across multiple files, primarily focusing on enhancing tournament-related functionalities, improving code readability, and ensuring proper handling of edge cases. The most significant changes include the addition of a new `TournamentModel` class, updates to scrim and tournament logic, and improvements to message handling.
* Added `TournamentModel` class in `src/ext/models/tournament.py` to represent tournament-related data with validation, caching, and database interaction capabilities. This includes properties like `guild_id`, `reg_channel`, `slot_channel`, and methods for saving and fetching tournaments.
* Updated `src/ext/models/__init__.py` to include `TournamentModel` in the module exports.
* Enhanced scrim creation logic in …

feat: Implement tournament model with validation and database

---

src/cogs/esports/scrim.py
src/cogs/esports/tourney.py
src/modules/message_handle.py

This pull request introduces several updates to the `src/cogs/esports/scrim.py`, `src/cogs/esports/tourney.py`, and `src/modules/message_handle.py` files, focusing on enhancing functionality, improving error handling, and refining user interactions. Key changes include adding new parameters to logging methods, simplifying scrim setup, improving role validation, and refining tournament management features.
* Added a `mention` parameter to the `log` method in `src/cogs/esports/scrim.py` to allow pinging specific roles in scrim log messages.
* Simplified scrim creation by directly using the `log` method instead of redundant helper calls.
* Removed unnecessary parameters (`slot_per_group`) in scrim group setup, streamlining the setup process. …

fix: Enhance scrim and tournament logging, improve role checks

---

src/cogs/__init__.py
src/cogs/dev.py
src/cogs/esports/scrim.py
src/cogs/helpcog.py
src/cogs/role.py
src/modules/.env-example
src/modules/bot.py

hide developer commands in DevCog; enhance role management commands with better error handling and descriptions

refactor: Update import statements for consistency and clarity; 

---

src/cogs/esports/scrim.py
src/cogs/esports/tourney.py
src/cogs/music.py
src/ext/checks.py

This pull request includes several updates across different modules to improve code readability, fix bugs, and streamline functionality. The most significant changes involve bug fixes in interaction handling, adjustments to role-based checks, and cleanup of unused code in the music module.
* **Fixed mention handling in scrim notifications**: Updated the logic in `async def on_scrim_open_time_hit` to properly handle mentions for default roles and custom roles.
* **Resolved `NoneType` error in interaction responses**: Added a conditional check in `async def on_interaction` to avoid errors when the interaction response is already sent.
* **Removed commented-out code in music module**: Deleted unused and commented-out code in `async def setup_lavalink` to improve readability.
* **Converted …

Minor bug fixes

---

src/cogs/esports/tourney.py

This pull request introduces a new command to the `tourney.py` cog that allows tournament moderators to change a team's name in a tournament. The command includes error handling for common issues such as missing channels or teams.
* **New Command Added**: A new `team_name` command has been implemented to allow tournament moderators to update a team's name. The command checks for valid registration and confirmation channels, verifies the team exists, and updates the name if all conditions are met.

feat: Add command to change team name in tournament

---

lava/application.yml
src/cogs/__init__.py
src/cogs/esports/__init__.py
src/cogs/esports/scrim.py
src/cogs/esports/tourney.py
src/cogs/migration/__init__.py
src/cogs/migration/tourney_cog.py
src/cogs/music.py
src/cogs/utility.py
src/ext/__init__.py
src/ext/_setup.py
src/ext/helper.py
src/ext/types/__init__.py
src/ext/types/bot_config.py
src/main.py
src/modules/bot.py
src/modules/config.py

This pull request includes several changes related to refactoring and enhancing functionality across multiple modules, particularly focusing on esports, music, and tournament-related features. The most notable updates include renaming and restructuring cogs, refining scrim and tournament logic, and overhauling music cog functionality to simplify and improve usability.
* Replaced `EsportsCog` with `TourneyCog` in `src/cogs/__init__.py` and `src/cogs/esports/__init__.py` to better reflect its purpose. Updated all relevant imports and `__all__` declarations accordingly. [[1]](diffhunk://#diff-b291230a47dac0d466b8065912bf92bd6492086614ad12277bb8136f4f8248ffL14-R14) [[2]](diffhunk://#diff-b291230a47dac0d466b8065912bf92bd6492086614ad12277bb8136f4f8248ffL33-R35) …

Tourney module migration and music refactors

---

.vscode/settings.json
src/cogs/__init__.py
src/cogs/dev.py
src/cogs/esports/scrim.py
src/cogs/esports/tourney.py
src/cogs/music.py
src/cogs/utility.py
src/ext/constants.py
src/ext/db.py
src/ext/types/errors.py
src/main.py
src/modules/bot.py
src/modules/chat.py
src/modules/checker.py
src/modules/message_handle.py

This pull request introduces various improvements, bug fixes, and refactorings across multiple cogs in the codebase. Key changes include the removal of the `MusicCog`, updates to tournament-related functionality, enhanced error handling in the music cog, and cleanup of unused or redundant code. Below is a categorized summary of the most important changes:
* Removed `MusicCog` from the list of active cogs in `src/cogs/__init__.py`. This reflects the temporary removal of the music functionality.
* Refactored button naming conventions in `src/cogs/esports/tourney.py` for consistency (e.g., `exportButton` renamed to `export_button`, `cancelButton` renamed to `cancel_button`). [[1]](diffhunk://#diff-4d0dc56d483143254eabe5ea66f10b48edf1b5d805bfa42d3bb87214e5e86cefL704-R703) …

feat: refactor cogs and improve error handling; add voice error handling

---

src/cogs/esports/tourney.py
src/main.py
src/modules/bot.py

fix(main): change error logging to print for better visibility
refactor(bot): clean up whitespace and improve comments in bot initialization

feat(tourney): add alias for config command to improve usability

---

LICENSE
src/cogs/dev.py
src/cogs/esports/scrim.py
src/cogs/esports/tourney.py
src/cogs/helpcog.py
src/cogs/moderation.py
src/cogs/music.py
src/cogs/role.py
src/cogs/utility.py
src/ext/__init__.py
src/ext/checks.py
src/ext/constants.py
src/ext/db.py
src/ext/error.py
src/ext/helper.py
src/ext/logger.py
src/ext/modals.py
src/ext/time.py
src/main.py
src/modules/bot.py
src/modules/chat.py
src/modules/checker.py
src/modules/message_handle.py
src/modules/payment.py

Revert "Development"

---

pyproject.toml
src/cogs/dev.py
src/cogs/esports/tourney.py
src/core/bot.py
src/ext/__init__.py
src/ext/cache.py
src/ext/helper.py
uv.lock

This pull request introduces several changes across two files, `src/cogs/dev.py` and `src/cogs/esports/tourney.py`, to enhance functionality and improve code structure. Key updates include the addition of a new command for role management, caching mechanisms for better performance, and refactoring of tournament-related logic to streamline operations.
* Added the `add_role` hybrid command, allowing developers to assign roles to members in specific guilds. Includes validation for guild, member, and role existence, as well as checks against default and bot-managed roles or roles above the bot's hierarchy.
* Introduced a `TTLCache` for caching confirmation messages by channel ID, reducing the need for repeated database queries.
* Replaced direct database queries with the `Tourney.findOne` …

Tourney Optimization (lil)

---

src/cogs/moderation.py

This pull request enhances the moderation functionality in `src/cogs/moderation.py` by introducing an `unban` command, improving server management capabilities. The most notable changes include the addition of the `unban` command with support for unbanning individual users or all banned users in bulk, and ensuring proper rate limiting and feedback during bulk operations.
* **`unban` command**: Added a new `unban` command that allows moderators to unban a specific user or all banned users (up to 2000 at a time). The command includes rate-limiting, feedback messages during bulk unbanning, and error handling for invalid inputs.
* **Rate limiting during bulk unbanning**: Implemented a sleep interval (`await self.bot.sleep(0.5)`) to avoid hitting Discord's rate limits during bulk unban …

Add unban command to ModerationCog for unbanning users from the server

---

src/cogs/esports/tourney.py
src/cogs/moderation.py
src/config.py

This pull request includes updates to improve error handling, optimize rate-limit management, and enhance configuration flexibility in the codebase. The most important changes involve refining exception handling in the `confirmed_cancel_slot` method, updating the unban functionality to avoid rate limits, and introducing a new configuration parameter for maximum unban limits.
* [`src/cogs/esports/tourney.py`](diffhunk://#diff-4d0dc56d483143254eabe5ea66f10b48edf1b5d805bfa42d3bb87214e5e86cefR1670-R1675): Improved error handling in `confirmed_cancel_slot` by replacing a conditional check with a `try-except` block to handle exceptions when fetching messages, ensuring better user feedback if a slot is not found or deleted.
* [`src/cogs/moderation.py`](diffhunk://#diff-6b6c8e9c427ff99063a8857a5a6 …

Enhance error handling in slot cancellation and update unban command

---

src/cogs/__init__.py
src/cogs/esports/__init__.py
src/cogs/esports/tourney/__init__.py
src/cogs/esports/tourney/esports.py
src/cogs/migration/__init__.py
src/models/tourney.py

This pull request introduces a new `Esports` cog, refactors the `TourneyModel` class, and removes the `TourneyMigrateCog`. The changes streamline the tournament management system and add functionality for esports-related features.
* Added the `Esports` cog to the project, integrating it into the development environment and the `__all__` exports in `src/cogs/esports/__init__.py` and `src/cogs/esports/tourney/__init__.py`. (`[[1]](diffhunk://#diff-b291230a47dac0d466b8065912bf92bd6492086614ad12277bb8136f4f8248ffR46-R48)`, `[[2]](diffhunk://#diff-2b076910a802ab20a4ae97da92c7869fd8d0046cbf9a891e9da0d49ed4859d58L2-R8)`, `[[3]](diffhunk://#diff-d0de636a02a900761ccbc026e1e3a079456472e97f99ba62ba7925d3317f2f57L2-R5)`)
* Renamed fields in the `TournamentPayload` class to use shorter, more concise …

Migrating old tourney module to new one
